version: '2'

services:
    api:
        build: ./FashionSense_WebApp
        container_name: api
        image: api_image
        # volumes:
        #     - .:/app
        expose:
            - "8080"
    ml:
        build: ./FashionSense_ML
        container_name: ml
        image: ml_image
        expose:
            - "5000"
    front:
        build: ./FashionSense_Front
        container_name: front
        image: front_image
        links:
            - api
            - ml
        ports:
            - "80:80"
