version: '2'

services:
    docs:
        build: ./FashionSense_Docs
        container_name: docs
        image: docs_image
        expose:
            - "4567"
        restart: always
    ml:
        build: ./FashionSense_ML
        container_name: ml
        image: ml_image
        volumes:
            - ./FashionSense_ML:/app
        expose:
            - "5000"
        restart: always
    front:
        build: ./FashionSense_Front
        container_name: front
        image: front_image
        links:
            - docs
            - ml
        ports:
            - "80:80"
        restart: always
