version: '2'

services:
    # api:
    #     build: ./FashionSense_WebApp
    #     container_name: api
    #     image: api_image
    #     volumes:
    #         - ./FashionSense_WebApp:/app
    #         - /tmp
    #     expose:
    #         - "8080"
    #     restart: always
    ml:
        build: ./FashionSense_ML
        container_name: ml
        image: ml_image
        volumes:
            - ./FashionSense_ML:/app
        expose:
            - "5000"
        restart: always
        # volumes_from:
        #     - api
    front:
        build: ./FashionSense_Front
        container_name: front
        image: front_image
        links:
            # - api
            - ml
        ports:
            - "80:80"
        restart: always
