version: '2'

services:
    front:
        build: ./front
        container_name: front
        image: front
        links:
            - api
        ports:
            - "80:80"
    api:
        build: ./api
        container_name: api
        image: api
        expose:
            - "8080"
