version: '2'

services:
    front:
        build: ./FashionSense_Front
        container_name: front
        image: front_image
        links:
            - webapp
            - ml
        ports:
            - "80:80"
    webapp:
        build: ./FashionSense_WebApp
        container_name: webapp
        image: webapp_image
        expose:
            - "8080"
    ml:
        build: ./FashionSense_ML
        container_name: ml
        image: ml_image
        expose:
            - "5000"
